### ISSUE TITLE
wp_editor glitches

### ISSUE THREAD

**Issue by booruguru** [booruguru/Job-Board-Creator#1]
For some reason wp_editor is not automatically creating paragraphs upon line breaks.

Also, when submitting posts that contain HTML, the formatting is displayed as expected. But when attempting to edit a post the html brackets are converted into alternative characters (which causes the tags to be displayed, not rendered, in the frontend). This is a big problem that needs to be fixed.

**Comment by guillaumer** [comment]
Issue is assigned to plugin when it should be to theme.
If you want to recreate it for the theme repository, I can push the corrections there.

**Comment by booruguru** [comment]
Ok, go ahead.

**Comment by guillaumer** [comment]
Fixed in theme repository.

booruguru/Job-Board-Framework@387ffc5a7b8087a174614cc523613a58727ae634
