### ISSUE TITLE
posts are still invisible on the jobs archive page

### ISSUE THREAD

**Issue by booruguru** [booruguru/Job-Board-Creator#2]
I can't see posts on the jobs archive page...again.
I have modified some of the files, so I may have done something to cause this problem to return.

**Comment by guillaumer** [comment]
Can you provide me a front/back access to where this is happening? They all
seems to appear on my environment.

2015-05-28 23:49 GMT+02:00 booruguru notifications@github.com:

**Comment by booruguru** [comment]
It should be the same test server we have been using.

http://45.55.159.135/jobs/

**Comment by guillaumer** [comment]
Hello, could you try with replacing this file?

It comes from the style not been assigned to the view. I think I had fixed
it before, but maybe the correction got lost in the transition to GitHub.
I'll push fix to Github if it's ok.

Regards.

2015-05-30 22:35 GMT+02:00 booruguru notifications@github.com:

**Comment by booruguru** [comment]
Go ahead.

**Comment by guillaumer** [comment]
Fixed in theme repository.

booruguru/Job-Board-Framework@6f9d5998db011d2493ea7afcb91917ecf0f48256
